# Generated by Django 3.2.9 on 2023-04-07 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_court', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_filed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 31, 15, 160170)),
        ),
        migrations.AlterField(
            model_name='case',
            name='status_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 31, 15, 160170)),
        ),
        migrations.AlterField(
            model_name='casenotes',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 31, 15, 160170)),
        ),
        migrations.AlterField(
            model_name='changes',
            name='date_changed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 31, 15, 175289)),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 31, 15, 162712)),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 14, 1, 15, 161768)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 31, 15, 161768)),
        ),
        migrations.AlterField(
            model_name='eventnote',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 31, 15, 162712)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 31, 15, 167714)),
        ),
    ]
