# Generated by Django 3.2.9 on 2023-04-07 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_court', '0003_auto_20230407_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_filed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 34, 59, 723096)),
        ),
        migrations.AlterField(
            model_name='case',
            name='status_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 34, 59, 723096)),
        ),
        migrations.AlterField(
            model_name='casenotes',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 34, 59, 724098)),
        ),
        migrations.AlterField(
            model_name='changes',
            name='date_changed',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 34, 59, 741095)),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 34, 59, 726097)),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 14, 4, 59, 726097)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 34, 59, 726097)),
        ),
        migrations.AlterField(
            model_name='eventnote',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 34, 59, 726097)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 34, 59, 731096)),
        ),
    ]
