from django.contrib import admin

from .models import *
# Register your models here.
admin.site.register(User)
admin.site.register(ChargeCode)
admin.site.register(ChargeClass)
admin.site.register(Charge)
admin.site.register(Judge)
admin.site.register(CourtOfficial)
admin.site.register(CaseSecurity)
admin.site.register(CaseStatus)
admin.site.register(CaseLocation)
admin.site.register(CaseType)
admin.site.register(Case)
admin.site.register(CaseNotes)
admin.site.register(EventType)
admin.site.register(Event)
admin.site.register(EventNote)
admin.site.register(DocumentType)
admin.site.register(Document)
admin.site.register(Address)
admin.site.register(Contact)
admin.site.register(Attorney)
admin.site.register(Participant)
admin.site.register(FeeCode)
admin.site.register(Fee)
admin.site.register(ParticipantFeeJoin)
admin.site.register(Mover)
admin.site.register(Responder)
admin.site.register(MoverCounsel)
admin.site.register(ResponderCounsel)
admin.site.register(PaymentType)
admin.site.register(Payment)